version: 2.1

commands:
  install_conda:
    description: "Install miniconda"
    steps:
      - checkout
      - run:
          name: install apt requirements
          command: |
            sudo apt-get update
            sudo apt-get install libgl1-mesa-glx libegl1-mesa-dev
      - run:
          name: Install conda
          command: |
            echo ""
            echo "Installing a fresh version of Miniconda."
            MINICONDA_URL="https://repo.continuum.io/miniconda"
            MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
            curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
            bash $MINICONDA_FILE -bp $HOME/miniconda3
  build_docs:
    description: Install and build the docs
    steps:
      - run:
          name: Install the conda environment
          command: |
            which conda || source $HOME/miniconda3/bin/activate base
            conda env create -f .circleci/environment.yml -n docs
      - run:
          name: Build the docs
          command: |
            which conda || source $HOME/miniconda3/bin/activate base
            conda activate docs
            sphinx-build . _build

jobs:
  build_docs:
    working_directory: ~/repo
    machine: true
    steps:
      - install_conda
      - build_docs
      - store_artifacts:
          path: ~/repo/_build
          destination: docs

  deploy_docs:
    docker:
      - image: node:latest
    steps:
      - checkout
      - attach_workspace:
          at: _build
      - run:
          name: Disable jekyll builds
          command: touch _build/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g gh-pages
            git config user.email "ci-build@psyplot.org"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "59:ad:fd:64:71:eb:81:01:6a:d7:1a:c9:0c:19:39:af"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "CircleCi Build ${CIRCLE_BUILD_NUM}, commit ${CIRCLE_SHA1} [skip ci]" --dist _build

workflows:
  version: 2.1
  build_docs:
    jobs:
      - build_docs
      - deploy_docs:
          requires:
            - build_docs
          filters:
            branches:
              only: main
